# Generated by Django 3.2.5 on 2022-04-30 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ovc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='ucid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderhistory', to='ovc_app.usercardinformation'),
        ),
        migrations.AlterField(
            model_name='usercardinformation',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usercardinfo', to='ovc_app.card'),
        ),
    ]
